version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./compose/docker/Dockerfile-dev
    command: bash -c "
      python manage.py makemigrations &&
      python manage.py migrate --fake-initial &&
      python manage.py loaddata ./fixtures/* &&
      python manage.py runscript create_tables &&
      python manage.py runscript populate_macapa &&
      python manage.py runscript populate_varejao &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./compose/docker/envfile.env
    depends_on:
      - mysql
      - postgresql

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"