# Generated by Django 2.2.24 on 2021-07-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VarejaoContact',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'contacts',
                'managed': True,
            },
        ),
    ]
