# Generated by Django 2.2.24 on 2021-07-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varejao', '0002_auto_20210708_0242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varejaocontact',
            options={
                'get_latest_by': ['pk'],
                'managed': True,
                'ordering': ['nome'],
                'verbose_name': 'Contato Varejão',
                'verbose_name_plural': 'Contatos Varejão'},
        ),
    ]
