FROM python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update -y
RUN apt-get install -y \
    build-essential \
    libgnutls28-dev \
    python-dev \
  && rm -rf /var/lib/apt/lists/*

COPY ./requirements/ /requirements/
RUN pip install --upgrade pip
RUN pip install sqlalchemy
RUN pip install -r /requirements/dev.txt

WORKDIR /code
